/**
 * Waveshare Controls HAL Implementation
 */

#include "hal/controls/hal_controls_waveshare.h"
#include "devices/waveshare/device_config.h"
#include <Arduino.h>

HALControlsWaveshare::HALControlsWaveshare()
    : callback_(nullptr)
    , enabled_(true) {
}

bool HALControlsWaveshare::begin() {
    Serial.println("[HAL-Controls-Waveshare] Initializing touch controls...");

    // Touch screen is initialized and managed by UIManager
    // Control events are generated by UI button callbacks

    Serial.println("[HAL-Controls-Waveshare] ✓ Controls HAL initialized");
    return true;
}

void HALControlsWaveshare::update() {
    // Touch processing is handled by LVGL in UIManager::update()
    // No additional processing needed here
}

void HALControlsWaveshare::registerCallback(ControlCallback callback) {
    callback_ = callback;

    // Note: The actual connection between UI button presses and control events
    // will be handled by UIManager, which should call this callback when
    // buttons are pressed. This may require updating UIManager to support
    // the HAL callback pattern.
}

bool HALControlsWaveshare::hasTouchScreen() const {
    return DEVICE_HAS_TOUCHSCREEN;
}

bool HALControlsWaveshare::hasPhysicalControls() const {
    return DEVICE_HAS_PHYSICAL_BUTTONS;
}

void HALControlsWaveshare::setEnabled(bool enabled) {
    enabled_ = enabled;
    // Could disable touch input here if needed
}

int HALControlsWaveshare::getVolumeDial() const {
    // No physical volume dial on Waveshare device
    return -1;
}

bool HALControlsWaveshare::getMuteSwitch() const {
    // No hardware mute switch on Waveshare device
    return false;
}
