#!/usr/bin/env python3
"""
Pre-build script to generate build_config.h from environment variables.
This allows configuration values to be set at build time without hardcoding them.
"""

import os
import sys

def get_env_or_default(key, default):
    """Get environment variable or return default value."""
    return os.environ.get(key, default)

def main():
    # Read configuration from environment variables
    room_name = get_env_or_default('ROOM_NAME', 'Unconfigured')
    wifi_ssid = get_env_or_default('WIFI_SSID', 'your-wifi-ssid')
    wifi_password = get_env_or_default('WIFI_PASSWORD', 'your-wifi-password')
    mqtt_broker = get_env_or_default('MQTT_BROKER', 'your-mqtt-broker-ip')
    mqtt_port = get_env_or_default('MQTT_PORT', '1883')
    mqtt_username = get_env_or_default('MQTT_USERNAME', 'homeassistant')
    mqtt_password = get_env_or_default('MQTT_PASSWORD', 'your-mqtt-password')
    ollama_host = get_env_or_default('OLLAMA_HOST', 'http://your-server-ip:11434')
    piper_host = get_env_or_default('PIPER_HOST', 'http://your-server-ip:10200')
    ha_host = get_env_or_default('HA_HOST', 'http://your-server-ip:8123')
    ha_token = get_env_or_default('HA_TOKEN', 'your_ha_token_here')

    # Generate header file content
    header_content = f"""// Auto-generated configuration file
// Generated by scripts/generate_config.py
// DO NOT EDIT - This file is overwritten on each build

#ifndef BUILD_CONFIG_H
#define BUILD_CONFIG_H

// Room Configuration
#define BUILD_ROOM_NAME "{room_name}"

// WiFi Configuration
#define BUILD_WIFI_SSID "{wifi_ssid}"
#define BUILD_WIFI_PASSWORD "{wifi_password}"

// MQTT Configuration
#define BUILD_MQTT_BROKER "{mqtt_broker}"
#define BUILD_MQTT_PORT {mqtt_port}
#define BUILD_MQTT_USERNAME "{mqtt_username}"
#define BUILD_MQTT_PASSWORD "{mqtt_password}"

// AI Services Configuration
#define BUILD_OLLAMA_HOST "{ollama_host}"
#define BUILD_PIPER_HOST "{piper_host}"
#define BUILD_HA_HOST "{ha_host}"
#define BUILD_HA_TOKEN "{ha_token}"

#endif // BUILD_CONFIG_H
"""

    # Write to include/build_config.h
    output_path = os.path.join('include', 'build_config.h')
    os.makedirs('include', exist_ok=True)

    with open(output_path, 'w') as f:
        f.write(header_content)

    print(f"[Config] Generated {output_path}")
    print(f"[Config]   Room Name: {room_name}")
    print(f"[Config]   WiFi SSID: {wifi_ssid}")
    print(f"[Config]   MQTT Broker: {mqtt_broker}:{mqtt_port}")
    print(f"[Config]   MQTT User: {mqtt_username}")
    print(f"[Config]   Ollama: {ollama_host}")
    print(f"[Config]   Piper: {piper_host}")
    print(f"[Config]   Home Assistant: {ha_host}")
    # Mask HA token in output for security
    token_masked = "********" if ha_token != "your_ha_token_here" else "not configured"
    print(f"[Config]   HA Token: {token_masked}")

if __name__ == '__main__':
    main()
